github:
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
  protected_branches:
    master: {}
  pull_requests:
    del_branch_on_merge: true
notifications:
  jira_options: "link"
  pullrequests_bot_sonarcloud: "commits@sling.apache.org"
